### PR TITLE
Mailmap Support and Other Changes

### LINKED ISSUE #19: Same author but with different names
I have a repository where some authors show up multiple times. For example "John Doe" and "john.doe".  This names should match, currently don't.

### PR DESCRIPTION
**Pull request by coffee-dan**
# Fixes and Features

I really enjoyed this game and have put together this PR in hopes of addressing all of the issues I found while playing. **The main issue is mailmap support**. Let me know what you think. :)

### Use name defined in mailmap
See: [Git - git-log Documentation author name](https://git-scm.com/docs/git-log#Documentation/git-log.txt-emaNem)

To utilize the local mailmap definition of committers the `--pretty` format string must use `%aN`.

This resolves #19 

---
### Handle bad input
Git game will exit if git itself cannot handle the custom input provided.

image

This is similar to #30 

---
### Use up to date Git documentation links
Used in README and help text

Dead link: http://gitref.org/inspect/
Official documentation: https://git-scm.com/docs/git-log

---
### Accept a variety of help args
`git game --help` and `git game -h` now accepted

image

## New Features

----
### Commit stats
Along with name and date, show a short description of changes.

image

---
### End the game when all commits have been shown
Git game will exit once all commits have been shown, congratulating the user and showing longest streak.

image

This is similar to #30 

---

This is based on feedback I got from friends that the game moves a little too fast.

image

### CODE REVIEW

**Comment by jsomers** [comment]
Hi, thanks so much for this! Can I ask for one little change: I like showing the "Commit stats" by default, but could you add a command-line argument like `--hard` where those are once again hidden?

**Comment by coffee-dan** [comment]
> Hi, thanks so much for this! Can I ask for one little change: I like showing the "Commit stats" by default, but could you add a command-line argument like `--hard` where those are once again hidden?

That sounds perfect! I will add a commit for that later today. :)

**Comment by coffee-dan** [comment]
@jsomers I added a couple commits for the `--hard` option. We can call `git game` with a combination of `--hard` and any number of `git` flags. So `git game --hard --after={2023-01-01}` works perfectly 🎉.

**Comment by coffee-dan** [comment]
Thank you for merging! Since there's now a couple new features, it might be a good idea to [create a new release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) and [bump the Homebrew formula](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula). What do you think? And if you would like me to take care of any of that for you let me know!

**Comment by jsomers** [comment]
If it's not too much trouble for you to take a crack, have at it! Let me know if you need me to make you a collaborator on the repo or anything. (As you can see, I'm pretty slow here :P)

**Comment by coffee-dan** [comment]
> If it's not too much trouble for you to take a crack, have at it! Let me know if you need me to make you a collaborator on the repo or anything. (As you can see, I'm pretty slow here :P)

Ok, I will put together a PR! Being a collaborator would be super helpful for creating a new release, thank you so much. I appreciate your help so far, I didn't even expect a response at all so slow responses are amazing in comparison.

**Comment by jsomers** [comment]
@coffee-dan I invited you to be a collaborator. Thanks for the help so far!

**Pull request merged**
